# Module_rollover
matrix:
  include:    
    - language: c  
      sudo: false # only for faster builds  
      compiler:
       - gcc
      script:  
       - gcc -o Rollover Rollover.c 
       - ./Rollover
